#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

#./download_deps

#ant -buildfile android-store-bazaar.xml -Dlogging="true" -Dsoomla.filename="Soomla_debug" all
#ant -buildfile android-store-bazaar.xml -Dlogging="false" -Dsoomla.filename="Soomla_release" all
ant -buildfile android-store-bazaar.xml -Dsoomla.filename="AndroidStoreBazaar" all
mkdir -p build/billing-services/bazaar
mv build/*.jar build/billing-services/bazaar/
cp libs/IInAppBillingService.jar build/billing-services/bazaar/IInAppBillingServiceBazaar.jar
cp libs/java-jwt-2.1.0.jar build/billing-services/bazaar/java-jwt-2.1.0.jar

cd - > /dev/null
